### ISSUE TITLE
Making this repo compatible with django templates too

### ISSUE THREAD

**Issue by gbozee** [danidee10/Staticfy#1]
Nice initiative @danidee10 But it would be nice if this project was also compatible with django templates. So what this would mean is an additional args would be passed to the command line specifying the project type `django` or `flask`. You could make the default `flask` if nothing is passed. 

In order to accomplish this, the functionality needs to be abstracted out first. I would look into issueing a PR on this later.

**Comment by danidee10** [comment]
Staticfy is not only compatible with django. It can now support a lot of languages by adding the associated  framework and it's pattern to the **config**.py file
